"""Categorized HTB tools (runner + Tool Info cheat sheet)."""

TOOL_GROUPS = [
    {
        "id": "network",
        "name": "1. Network",
        "blurb": "Host discovery and port/service scans against the configured target.",
        "tools": [
            {
                "id": "nmap-sv",
                "name": "Nmap service / version",
                "bin": "nmap",
                "kind": "nmap",
                "nmap_args": ["-sV"],
                "summary": "nmap -sV TARGET — top 1000 TCP ports (nmap default), not the assigned lab port.",
                "purpose": "Identify reachable services and versions on default ports.",
            },
            {
                "id": "nmap-port",
                "name": "Nmap assigned port",
                "bin": "nmap",
                "kind": "nmap-port",
                "nmap_args": ["-sV"],
                "summary": "nmap -sV -p PORT TARGET — only the assigned/entered port.",
                "purpose": "Identify what is exposed on that one port.",
            },
            {
                "id": "nmap-full",
                "name": "Nmap all TCP ports",
                "bin": "nmap",
                "kind": "nmap",
                "nmap_args": ["-p-", "-sV"],
                "summary": "nmap -p- -sV TARGET — all 65535 TCP ports. Slow. Does not use the assigned lab port.",
                "purpose": "Find services on non-default ports.",
            },
            {
                "id": "nmap-udp",
                "name": "Nmap top UDP",
                "bin": "nmap",
                "kind": "nmap",
                "nmap_args": ["-sU", "--top-ports", "50"],
                "summary": "nmap -sU --top-ports 50 TARGET — top 50 UDP ports. Slow.",
                "purpose": "Check common UDP services.",
            },
            {
                "id": "ping",
                "name": "ping",
                "bin": "ping",
                "kind": "ping",
                "summary": "ping -c 4 TARGET (Windows: ping -n 4). ICMP echo only.",
                "purpose": "Check whether the target answers ICMP.",
            },
            {
                "id": "traceroute",
                "name": "traceroute / tracert",
                "bin": "tracert",
                "alt_bins": ["traceroute", "tracepath"],
                "kind": "traceroute",
                "summary": "Hop path. Windows: tracert TARGET. Linux: traceroute TARGET.",
                "purpose": "See the hop path to the target.",
            },
        ],
    },
    {
        "id": "web",
        "name": "2. Web / Fuzzing",
        "blurb": "Content discovery, vhosts, and web fingerprinting.",
        "tools": [
            {
                "id": "gobuster-dir",
                "name": "Gobuster dir",
                "bin": "gobuster",
                "kind": "gobuster",
                "mode": "dir",
                "summary": "gobuster dir -u URL -w wordlist — directory/file brute force.",
                "purpose": "Enumerate web paths on the target.",
                "fields": [
                    {"name": "url", "label": "Target URL", "default": "http://{target}"},
                    {"name": "wordlist", "label": "Wordlist", "default": ""},
                ],
            },
            {
                "id": "ffuf",
                "name": "ffuf",
                "bin": "ffuf",
                "kind": "template",
                "argv": ["ffuf", "-u", "{url}", "-w", "{wordlist}"],
                "summary": "ffuf -u URL-with-FUZZ -w wordlist. Put FUZZ where the word goes.",
                "purpose": "Fuzz directories, parameters, or vhosts.",
                "fields": [
                    {"name": "url", "label": "URL (include FUZZ)", "default": "http://{target}/FUZZ"},
                    {"name": "wordlist", "label": "Wordlist", "default": ""},
                ],
            },
            {
                "id": "feroxbuster",
                "name": "Feroxbuster",
                "bin": "feroxbuster",
                "kind": "template",
                "argv": ["feroxbuster", "-u", "{url}", "-w", "{wordlist}"],
                "summary": "feroxbuster -u URL -w wordlist — recursive content discovery.",
                "purpose": "Crawl and brute-force web content.",
                "fields": [
                    {"name": "url", "label": "Target URL", "default": "http://{target}"},
                    {"name": "wordlist", "label": "Wordlist", "default": ""},
                ],
            },
            {
                "id": "nikto",
                "name": "Nikto",
                "bin": "nikto",
                "kind": "template",
                "argv": ["nikto", "-h", "{url}"],
                "summary": "nikto -h URL — common web misconfigs and known files.",
                "purpose": "Look for obvious web server issues.",
                "fields": [{"name": "url", "label": "Target URL", "default": "http://{target}"}],
            },
            {
                "id": "whatweb",
                "name": "WhatWeb",
                "bin": "whatweb",
                "kind": "template",
                "argv": ["whatweb", "-a", "3", "{url}"],
                "summary": "whatweb -a 3 URL — fingerprint CMS, language, and headers.",
                "purpose": "Identify CMS, language, and server stack.",
                "fields": [{"name": "url", "label": "Target URL", "default": "http://{target}"}],
            },
        ],
    },
    {
        "id": "dns",
        "name": "3. DNS / OSINT",
        "blurb": "Name resolution and public record lookups. Only against authorized names.",
        "tools": [
            {
                "id": "dig",
                "name": "dig",
                "bin": "dig",
                "kind": "template",
                "argv": ["dig", "{query}"],
                "summary": "dig NAME — DNS lookup (A/AAAA/MX/NS/TXT).",
                "purpose": "Resolve authorized hostnames.",
                "fields": [{"name": "query", "label": "Name / query", "default": ""}],
            },
            {
                "id": "nslookup",
                "name": "nslookup",
                "bin": "nslookup",
                "kind": "template",
                "argv": ["nslookup", "{query}"],
                "summary": "nslookup NAME — DNS lookup; works on Windows labs too.",
                "purpose": "Resolve authorized hostnames.",
                "fields": [{"name": "query", "label": "Name / query", "default": ""}],
            },
            {
                "id": "whois",
                "name": "whois",
                "bin": "whois",
                "kind": "template",
                "argv": ["whois", "{query}"],
                "summary": "whois DOMAIN-or-IP — public registration records.",
                "purpose": "Gather public registration data for an authorized name.",
                "fields": [{"name": "query", "label": "Domain / IP", "default": ""}],
            },
            {
                "id": "host",
                "name": "host",
                "bin": "host",
                "kind": "template",
                "argv": ["host", "{query}"],
                "summary": "host NAME — quick A/AAAA/MX check.",
                "purpose": "Quick A/AAAA/MX check.",
                "fields": [{"name": "query", "label": "Name", "default": ""}],
            },
        ],
    },
    {
        "id": "smb",
        "name": "4. SMB / AD",
        "blurb": "Windows/Samba enumeration. No spraying or brute force from this helper.",
        "tools": [
            {
                "id": "enum4linux",
                "name": "enum4linux-ng",
                "bin": "enum4linux-ng",
                "kind": "template",
                "argv": ["enum4linux-ng", "-A", "{target}"],
                "summary": "enum4linux-ng -A TARGET — shares, users, and policy if exposed.",
                "purpose": "Collect shares, users, and policy info if exposed.",
                "alt_bins": ["enum4linux"],
            },
            {
                "id": "smbclient",
                "name": "smbclient shares",
                "bin": "smbclient",
                "kind": "template",
                "argv": ["smbclient", "-N", "-L", "{target}"],
                "summary": "smbclient -N -L TARGET — list shares with no password.",
                "purpose": "See which shares are visible without credentials.",
            },
            {
                "id": "nxc-smb",
                "name": "NetExec smb",
                "bin": "nxc",
                "kind": "template",
                "argv": ["nxc", "smb", "{target}"],
                "summary": "nxc smb TARGET — dialect, signing, hostname. No spraying.",
                "purpose": "Identify SMB dialect, signing, and hostname.",
                "alt_bins": ["netexec", "crackmapexec"],
            },
            {
                "id": "ldapsearch",
                "name": "ldapsearch",
                "bin": "ldapsearch",
                "kind": "template",
                "argv": ["ldapsearch", "-x", "-H", "ldap://{target}", "-s", "base", "namingcontexts"],
                "summary": "ldapsearch -x -H ldap://TARGET -s base namingcontexts.",
                "purpose": "See if LDAP answers and which naming contexts exist.",
            },
        ],
    },
    {
        "id": "http",
        "name": "5. HTTP clients",
        "blurb": "Fetch headers or a URL and keep the raw response.",
        "tools": [
            {
                "id": "curl-headers",
                "name": "curl headers",
                "bin": "curl",
                "kind": "template",
                "argv": ["curl", "-sI", "{url}"],
                "summary": "curl -sI URL — response headers only.",
                "purpose": "Read server, redirect, and auth headers.",
                "fields": [{"name": "url", "label": "URL", "default": "http://{target}"}],
            },
            {
                "id": "wget",
                "name": "wget",
                "bin": "wget",
                "kind": "template",
                "argv": ["wget", "-S", "-O", "-", "{url}"],
                "summary": "wget -S -O - URL — headers plus body on stdout.",
                "purpose": "Fetch a page or file and keep the response.",
                "fields": [{"name": "url", "label": "URL", "default": "http://{target}"}],
            },
        ],
    },
    {
        "id": "custom",
        "name": "6. Custom",
        "blurb": "Any other authorized recon/enum command. Output is captured automatically — no | tee.",
        "tools": [
            {
                "id": "custom",
                "name": "Custom command",
                "bin": None,
                "kind": "custom",
                "summary": "Type the full command in the Command box. Output is captured — no extra command field.",
                "purpose": "",
                "fields": [],
            },
        ],
    },
]


TOOL_INFO = [
    {
        "group": "Network",
        "tools": [
            {
                "name": "Nmap",
                "bin": "nmap",
                "blurb": "Host discovery, port scans, service/version, and NSE scripts.",
                "syntax": "nmap [scan type] [options] {target}",
                "options": [
                    "-sV              service/version detection",
                    "-sC              default NSE scripts",
                    "-sU              UDP scan (slow)",
                    "-p-              all TCP ports",
                    "-p 22,80,443     specific ports",
                    "-Pn              skip host discovery (treat as up)",
                    "-A               OS + version + scripts + traceroute",
                    "-oN file.nmap    nmap text output (helper also saves a .txt capture)",
                    "--min-rate 1000  faster timing (noisier)",
                    "--script vuln    NSE vuln scripts (authorized labs only; noisy)",
                    "--script vuln,safe",
                    "-sV -sC          version + default scripts (good first pass)",
                    "--script http-enum,http-title",
                ],
                "examples": [
                    "nmap -sV -oN logs/scan.nmap $TARGET",
                    "nmap -p- -sV -oN logs/full.nmap $TARGET",
                    "nmap -sV -p $PORT -oN logs/port.nmap $TARGET",
                    "nmap -sV -sC --script vuln -oN logs/vuln.nmap $TARGET",
                    "nmap -sV --script vuln -p 80,443,8080 $TARGET",
                ],
            },
            {
                "name": "ping",
                "bin": "ping",
                "blurb": "ICMP echo to see if a host answers. Output is now captured in the session log.",
                "syntax": "ping [options] {target}",
                "options": [
                    "-n 4            Windows: count (default 4)",
                    "-c 4            Linux: count (required, or it runs until Ctrl+C)",
                    "-t              Windows: ping until stopped",
                    "-w 1000         timeout ms (Windows)",
                    "-W 1            timeout seconds (Linux)",
                ],
                "examples": [
                    "ping -n 4 $TARGET",
                    "ping -c 4 $TARGET",
                ],
            },
            {
                "name": "tracert / traceroute",
                "bin": "tracert",
                "blurb": "Hop-by-hop path. Windows is tracert; Parrot/Kali is traceroute. Ctrl+C stops it; logging continues.",
                "syntax": "tracert [options] {target}   |   traceroute [options] {target}",
                "options": [
                    "-d              Windows: do not resolve names",
                    "-h 30           Windows: max hops",
                    "-w 1000         Windows: per-hop timeout ms",
                    "-n              Linux: numeric, skip DNS",
                    "-m 30           Linux: max hops",
                ],
                "examples": [
                    "tracert $TARGET",
                    "traceroute -n $TARGET",
                ],
            },
            {
                "name": "Masscan",
                "bin": "masscan",
                "blurb": "Very fast TCP port sweep. Follow up interesting ports with nmap -sV.",
                "syntax": "masscan [options] {target}",
                "options": [
                    "-p80,443,1-65535   ports",
                    "--rate 1000        packets/sec",
                    "-oL file           list output",
                ],
                "examples": [
                    "masscan $TARGET -p1-65535 --rate 1000",
                ],
            },
        ],
    },
    {
        "group": "Web / Fuzzing",
        "tools": [
            {
                "name": "Gobuster",
                "bin": "gobuster",
                "blurb": "Brute-force directories, vhosts, or DNS names from a wordlist.",
                "syntax": "gobuster <mode> -u/-d <target> -w <wordlist> [options]",
                "options": [
                    "dir                 directory/file mode",
                    "vhost               virtual-host mode",
                    "dns                 subdomain mode",
                    "-u URL              base URL (dir/vhost)",
                    "-d domain           domain (dns)",
                    "-w wordlist         wordlist path",
                    "-t 40               threads",
                    "-x php,txt,html     extensions (dir)",
                    "--exclude-length N  drop a noisy size",
                ],
                "examples": [
                    "gobuster dir -u http://$TARGET -w /usr/share/wordlists/dirb/common.txt -x php,txt",
                    "gobuster vhost -u http://$TARGET -w /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt",
                ],
            },
            {
                "name": "ffuf",
                "bin": "ffuf",
                "blurb": "Fast fuzzer. Put FUZZ where the wordlist should substitute.",
                "syntax": "ffuf -u <url-with-FUZZ> -w <wordlist> [options]",
                "options": [
                    "-u URL              URL containing FUZZ",
                    "-w wordlist         wordlist (or wordlist:KEY)",
                    "-H 'Host: FUZZ'     header fuzz (vhosts)",
                    "-mc 200,204,301     match status codes",
                    "-fc 404             filter status",
                    "-fs 1234            filter response size",
                    "-e .php,.txt        extensions",
                    "-t 40               threads",
                    "-rate 20            req/sec cap",
                ],
                "examples": [
                    "ffuf -u http://$TARGET/FUZZ -w /usr/share/wordlists/dirb/common.txt -mc 200,204,301,302,403",
                    "ffuf -u http://$TARGET/ -H 'Host: FUZZ.$HOST' -w subdomains.txt",
                ],
            },
            {
                "name": "Feroxbuster",
                "bin": "feroxbuster",
                "blurb": "Recursive content discovery; follows directories as it finds them.",
                "syntax": "feroxbuster -u <url> -w <wordlist> [options]",
                "options": [
                    "-u URL        target",
                    "-w wordlist   wordlist",
                    "-x php,txt    extensions",
                    "-n            no recursion",
                    "--extract-links   harvest links from responses",
                    "-C 404        ignore status",
                ],
                "examples": [
                    "feroxbuster -u http://$TARGET -w /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt",
                ],
            },
            {
                "name": "Nikto",
                "bin": "nikto",
                "blurb": "Checks a web server for common misconfigurations and known files.",
                "syntax": "nikto -h <host|url> [options]",
                "options": [
                    "-h host     target host or URL",
                    "-p port     port",
                    "-ssl        force TLS",
                    "-Tuning x   enable/disable test classes",
                    "-output f   save report",
                ],
                "examples": [
                    "nikto -h http://$TARGET",
                ],
            },
            {
                "name": "WhatWeb",
                "bin": "whatweb",
                "blurb": "Fingerprints CMS, frameworks, headers, and plugins.",
                "syntax": "whatweb [options] {url}",
                "options": [
                    "-a 1..4     aggression (3 is a good default)",
                    "-v          verbose",
                    "--log-brief file",
                ],
                "examples": [
                    "whatweb -a 3 http://$TARGET",
                ],
            },
            {
                "name": "Nuclei",
                "bin": "nuclei",
                "blurb": "Template-based scanner for known web issues. Keep scope authorized.",
                "syntax": "nuclei -u <url> [options]",
                "options": [
                    "-u URL           target",
                    "-t templates/    template path",
                    "-severity info,low,medium,high,critical",
                    "-o file          output",
                ],
                "examples": [
                    "nuclei -u http://$TARGET -severity medium,high,critical",
                ],
            },
            {
                "name": "httpx",
                "bin": "httpx",
                "blurb": "Probe URLs/hosts for live HTTP(S) and grab titles/status.",
                "syntax": "httpx [options]",
                "options": [
                    "-u URL        single target",
                    "-l file       list of hosts",
                    "-title -status-code -tech-detect",
                    "-silent",
                ],
                "examples": [
                    "echo $TARGET | httpx -title -status-code -tech-detect",
                ],
            },
        ],
    },
    {
        "group": "DNS / OSINT",
        "tools": [
            {
                "name": "dig",
                "bin": "dig",
                "blurb": "DNS lookup. Use only on names in scope.",
                "syntax": "dig [@server] {name} [type]",
                "options": [
                    "A / AAAA / MX / NS / TXT / ANY",
                    "+short          one-line answers",
                    "+noall +answer  just the answer section",
                    "AXFR            zone transfer attempt (often blocked)",
                ],
                "examples": [
                    "dig $HOST A +short",
                    "dig @$TARGET $HOST ANY",
                ],
            },
            {
                "name": "nslookup",
                "bin": "nslookup",
                "blurb": "DNS lookup; available on Windows lab boxes too.",
                "syntax": "nslookup {name} [server]",
                "options": [
                    "set type=A|MX|NS|TXT",
                    "server {ip}     query that resolver",
                ],
                "examples": [
                    "nslookup $HOST",
                    "nslookup $HOST $TARGET",
                ],
            },
            {
                "name": "whois",
                "bin": "whois",
                "blurb": "Public registration records for a domain or IP block.",
                "syntax": "whois {domain|ip}",
                "options": [
                    "-h server   specific whois server",
                ],
                "examples": [
                    "whois example.com",
                ],
            },
            {
                "name": "host",
                "bin": "host",
                "blurb": "Small DNS client for a quick A/MX/NS check.",
                "syntax": "host [options] {name}",
                "options": [
                    "-t TYPE     query type",
                    "-a          all records",
                ],
                "examples": [
                    "host $HOST",
                ],
            },
        ],
    },
    {
        "group": "SMB / AD",
        "tools": [
            {
                "name": "enum4linux-ng",
                "bin": "enum4linux-ng",
                "blurb": "Bundled SMB/NetBIOS/LDAP enumeration (users, shares, policy).",
                "syntax": "enum4linux-ng [options] {target}",
                "options": [
                    "-A          all simple enumeration",
                    "-u user -p pass",
                    "-oJ file    JSON output",
                ],
                "examples": [
                    "enum4linux-ng -A $TARGET",
                ],
            },
            {
                "name": "smbclient",
                "bin": "smbclient",
                "blurb": "Talk to SMB shares: list, connect, get files.",
                "syntax": "smbclient [options] {//host/share}",
                "options": [
                    "-N              no password",
                    "-L host         list shares",
                    "-U user         username",
                    "//host/share    connect to a share",
                ],
                "examples": [
                    "smbclient -N -L //$TARGET",
                    "smbclient -N //$TARGET/public",
                ],
            },
            {
                "name": "NetExec (nxc)",
                "bin": "nxc",
                "blurb": "Modern CrackMapExec. Probe SMB/WinRM/LDAP. Do not use for spraying from this helper.",
                "syntax": "nxc <proto> {target} [options]",
                "options": [
                    "smb / ldap / winrm / ssh",
                    "-u user -p pass     authenticated",
                    "--shares            list shares",
                    "--users             list users (if allowed)",
                    "-x 'whoami'         command (authorized only)",
                ],
                "examples": [
                    "nxc smb $TARGET",
                    "nxc smb $TARGET --shares",
                ],
            },
            {
                "name": "rpcclient",
                "bin": "rpcclient",
                "blurb": "MS-RPC queries against a Windows/Samba host.",
                "syntax": "rpcclient [options] {target}",
                "options": [
                    "-U user          credentials",
                    "-N               no password",
                    "enumdomusers     (inside the shell)",
                    "querydominfo",
                ],
                "examples": [
                    "rpcclient -N $TARGET",
                ],
            },
            {
                "name": "ldapsearch",
                "bin": "ldapsearch",
                "blurb": "Raw LDAP queries. Start with a base namingContexts read.",
                "syntax": "ldapsearch [options] [filter [attrs]]",
                "options": [
                    "-x                 simple auth (often anonymous)",
                    "-H ldap://host     URI",
                    "-b 'DC=x,DC=y'     search base",
                    "-s base|one|sub    scope",
                    "-D user -w pass    bind",
                ],
                "examples": [
                    "ldapsearch -x -H ldap://$TARGET -s base namingcontexts",
                ],
            },
            {
                "name": "smbmap",
                "bin": "smbmap",
                "blurb": "Lists shares and permissions in one pass.",
                "syntax": "smbmap -H {host} [options]",
                "options": [
                    "-H host       target",
                    "-u user -p pass",
                    "-r SHARE      recurse a share",
                ],
                "examples": [
                    "smbmap -H $TARGET",
                ],
            },
        ],
    },
    {
        "group": "HTTP clients",
        "tools": [
            {
                "name": "curl",
                "bin": "curl",
                "blurb": "Fetch a URL. Use -I for headers, -k for lab TLS, -v for the handshake.",
                "syntax": "curl [options] {url}",
                "options": [
                    "-s          silent body",
                    "-I          headers only",
                    "-k          ignore TLS errors (labs)",
                    "-v          verbose",
                    "-A ua       user-agent",
                    "-H 'K: V'   extra header",
                    "-X POST -d data",
                    "-o file     save body",
                ],
                "examples": [
                    "curl -sI http://$TARGET",
                    "curl -sk https://$TARGET/",
                ],
            },
            {
                "name": "wget",
                "bin": "wget",
                "blurb": "Download files or mirror a path. Good for grabbing tools onto the box.",
                "syntax": "wget [options] {url}",
                "options": [
                    "-S          show server headers",
                    "-O file     output name (- is stdout)",
                    "-k          convert links (mirror)",
                    "--no-check-certificate",
                ],
                "examples": [
                    "wget -S -O - http://$TARGET/",
                ],
            },
        ],
    },
    {
        "group": "CTF / HTB extras",
        "tools": [
            {
                "name": "CyberChef",
                "bin": "browser",
                "blurb": "The encoding/decoding kitchen HTB materials usually point people to: ASCII, hex, Base64, hashes, magic.",
                "syntax": "https://gchq.github.io/CyberChef/",
                "options": [
                    "From Decimal     72 84 66 123 … → HTB{",
                    "From Hex         48 54 42 7b …",
                    "From Base64",
                    "Magic            try to auto-detect the encoding",
                    "To Decimal / To Hex   for the other direction",
                ],
                "examples": [
                    "Open https://gchq.github.io/CyberChef/",
                    "Recipe: From Decimal, delimiter Space, then read HTB{…}",
                ],
            },
            {
                "name": "Official CVE lookups",
                "bin": "browser",
                "blurb": "Look up a CVE ID on the official catalogs. Use these, not random blogs, as the first source.",
                "syntax": "https://nvd.nist.gov/   |   https://www.cve.org/",
                "options": [
                    "NVD              https://nvd.nist.gov/vuln/search",
                    "CVE Program      https://www.cve.org/",
                    "MITRE CVE        https://cve.mitre.org/cve/search_cve_list.html",
                    "CISA KEV         https://www.cisa.gov/known-exploited-vulnerabilities-catalog",
                    "CISA ICS         https://www.cisa.gov/topics/industrial-control-systems",
                ],
                "examples": [
                    "https://nvd.nist.gov/vuln/detail/CVE-2021-44228",
                    "https://www.cve.org/CVERecord?id=CVE-2021-44228",
                ],
            },
        ],
    },
    {
        "group": "ICS / SCADA / Modbus",
        "tools": [
            {
                "name": "Nmap Modbus",
                "bin": "nmap",
                "blurb": "Find Modbus/TCP (usually port 502) and list unit IDs. Authorized labs only.",
                "syntax": "nmap -sV -p 502 --script modbus-discover {target}",
                "options": [
                    "-p 502                    Modbus/TCP default",
                    "--script modbus-discover  unit-id / device id",
                    "-Pn                       skip ICMP if the PLC ignores ping",
                ],
                "examples": [
                    "nmap -sV -p 502 --script modbus-discover $TARGET",
                    "nmap -p 502,102,44818,47808 $TARGET",
                ],
            },
            {
                "name": "pymodbus client",
                "bin": "python3",
                "blurb": "Read/write coils and registers over Modbus/TCP. pip install pymodbus if needed. Authorized labs only.",
                "syntax": "from pymodbus.client import ModbusTcpClient",
                "options": [
                    "port 502                     Modbus/TCP",
                    "slave=1                      unit/slave id (often 1)",
                    "read_coils(addr, count)      discrete outputs",
                    "read_discrete_inputs(...)    discrete inputs",
                    "read_holding_registers(...)  analog/holding",
                    "read_input_registers(...)    analog inputs",
                    "write_coil(addr, bool)       write one coil",
                    "write_coils(addr, [bool…])   write many coils",
                    "write_register(addr, int)    write one holding register",
                    "write_registers(addr, [int…]) write many",
                ],
                "examples": [
                    "from pymodbus.client import ModbusTcpClient",
                    "c = ModbusTcpClient('$TARGET', port=502)",
                    "c.connect()",
                    "print(c.read_coils(0, 16, slave=1).bits)",
                    "print(c.read_discrete_inputs(0, 16, slave=1).bits)",
                    "print(c.read_holding_registers(0, 10, slave=1).registers)",
                    "print(c.read_input_registers(0, 10, slave=1).registers)",
                    "c.write_coil(0, True, slave=1)",
                    "c.write_coils(0, [True, False, True], slave=1)",
                    "c.write_register(0, 1234, slave=1)",
                    "c.write_registers(0, [1, 2, 3, 4], slave=1)",
                    "c.close()",
                ],
            },
            {
                "name": "umodbus TCP",
                "bin": "python3",
                "blurb": "Smaller Modbus stack. pip install umodbus. Function codes: 1 coils, 2 discrete inputs, 3 holding, 4 input, 5/15 write coil(s), 6/16 write register(s).",
                "syntax": "from umodbus import conf; from umodbus.client import tcp",
                "options": [
                    "tcp.read_coils(slave, addr, count)",
                    "tcp.read_discrete_inputs(slave, addr, count)",
                    "tcp.read_holding_registers(slave, addr, count)",
                    "tcp.read_input_registers(slave, addr, count)",
                    "tcp.write_single_coil(slave, addr, 0xFF00 or 0)",
                    "tcp.write_multiple_coils(slave, addr, [1, 0, 1])",
                    "tcp.write_single_register(slave, addr, value)",
                    "tcp.write_multiple_registers(slave, addr, [1, 2, 3])",
                ],
                "examples": [
                    "import socket",
                    "from umodbus.client import tcp",
                    "sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)",
                    "sock.connect(('$TARGET', 502))",
                    "adu = tcp.send_message(tcp.read_coils(1, 0, 8), sock)",
                    "print(adu)",
                    "tcp.send_message(tcp.write_single_coil(1, 0, 0xFF00), sock)",
                    "tcp.send_message(tcp.write_multiple_registers(1, 0, [10, 20, 30]), sock)",
                    "sock.close()",
                ],
            },
            {
                "name": "Official ICS / Modbus docs",
                "bin": "browser",
                "blurb": "Primary references. Use these before random write-ups. Authorized labs only — do not scan or write coils on systems you do not own.",
                "syntax": "modbus.org  |  nist.gov SP 800-82  |  cisa.gov ICS",
                "options": [
                    "Modbus home              https://modbus.org/",
                    "Modbus specs             https://modbus.org/specs.php",
                    "Application Protocol     https://modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf",
                    "TCP/IP implementation    https://modbus.org/docs/Modbus_Messaging_Implementation_Guide_V1_0b.pdf",
                    "NIST SP 800-82 ICS       https://csrc.nist.gov/pubs/sp/800/82/r3/final",
                    "CISA ICS                 https://www.cisa.gov/topics/industrial-control-systems",
                    "CISA ICS advisories      https://www.cisa.gov/news-events/cybersecurity-advisories",
                    "CODESYS addresses        https://content.helpme-codesys.com/en/CODESYS%20Development%20System/_cds_operands_addresses.html",
                ],
                "examples": [
                    "https://modbus.org/specs.php",
                    "https://csrc.nist.gov/pubs/sp/800/82/r3/final",
                    "https://www.cisa.gov/topics/industrial-control-systems",
                ],
            },
            {
                "name": "ICS ports (cheat)",
                "bin": "ref",
                "blurb": "Common industrial ports to keep in mind on ICS boxes. Confirm the lab scope before scanning.",
                "syntax": "502 Modbus/TCP   102 S7comm   44818 EtherNet/IP   47808 BACnet   20000 DNP3   4840 OPC UA",
                "options": [
                    "502     Modbus/TCP",
                    "102     Siemens S7comm",
                    "44818   EtherNet/IP (Rockwell)",
                    "2222    EtherNet/IP extra",
                    "47808   BACnet",
                    "20000   DNP3",
                    "4840    OPC UA",
                    "1911    Niagara Fox",
                    "2404    IEC 60870-5-104",
                ],
                "examples": [
                    "nmap -sV -p 102,502,2404,4840,20000,44818,47808 $TARGET",
                ],
            },
        ],
    },
]


COMMON_WORDLISTS = [
    "/usr/share/wordlists/dirb/common.txt",
    "/usr/share/dirb/wordlists/common.txt",
    "/usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt",
    "/usr/share/seclists/Discovery/Web-Content/common.txt",
    "/usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt",
    "/usr/share/wordlists/wfuzz/general/common.txt",
    "/usr/share/wordlists/dirb/big.txt",
]
